name: Release New Version
on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          release-type: node
          package-name: typescript-language-server
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"refactor","section":"Refactors","hidden":false}]'
      - uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - run: corepack enable
      - name: Lint and Test
        if: ${{ steps.release.outputs.release_created }}
        run: yarn && yarn build && yarn lint
      - name: Publish to NPM
        if: ${{ steps.release.outputs.release_created }}
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
